### ISSUE TITLE
Token refresh on each API request when using UserAccessTokenCredentials

### ISSUE THREAD

**Issue by bzurkowski** [googleapis/google-auth-library-python#1341]
I observed that requests to Google Cloud APIs take much longer when using `UserAccessTokenCredentials` (documented [here](https://google-auth.readthedocs.io/en/stable/reference/google.oauth2._credentials_async.html#google.oauth2._credentials_async.UserAccessTokenCredentials)) as `credentials` for client libraries, e.g., Storage [library](https://github.com/googleapis/python-storage) for Python.

Diving into the code, I realized that `UserAccessTokenCredentials` triggers token refresh (resulting in an additional API request) on each request due to how the `before_request` method is [implemented](https://github.com/googleapis/google-auth-library-python/blob/v2.21.0/google/oauth2/credentials.py#L530):

```python
def before_request(self, request, method, url, headers):
    self.refresh(request)
    self.apply(headers)
```

In [comparison](https://github.com/googleapis/google-auth-library-python/blob/abedaa81f8f19fc34fad5687a0205cd7f71cd4fd/google/auth/credentials.py#L133), the `before_request` method in the base class has a mechanism to trigger token refresh only when necessary:

```python
if not self.valid:
    self.refresh(request)
```

Would it be reasonable to check token validity before request in the `UserAccessTokenCredentials` strategy?

**Comment by arithmetic1728** [comment]
I think `google.oauth2.credentials.Credentials` should be used instead. (In other words, you run `gcloud auth application-default login`, and let the client lib pick up the application default credentials on its own).

`google.oauth2.credentials.UserAccessTokenCredentials` simply runs `gcloud auth print-access-token` to get the token, this class doesn't even cache the token. To check the validity requires sending the token to some token info endpoint, simply checking `self.valid` won't work. I wouldn't recommend using this credential.  `google.oauth2.credentials.Credentials` is the one I recommend.

**Comment by arithmetic1728** [comment]
UserAccessTokenCredential was initially added for mTLS feature since at that time user credentials had issues (which is already fixed now). Therefore we want to deprecate UserAccessTokenCredential since it's google-auth specific, and not available in other languages. Users are recommended to use user credentials instead (google.oauth2.credentials.Credentials), which is a generic application default credential type available in all languages. To use it, simply run gcloud auth application-default login and let the client libraries automatically use it.
