### ISSUE TITLE
BigQuery: Flaky RefreshError: 'invalid_grant: Invalid JWT: No valid verifier found for issuer.'

### ISSUE THREAD

**Issue by bencaine1** [googleapis/google-auth-library-python#301]
We're getting a flaky error trying to authorize credentials. See [this issue](https://github.com/googleapis/google-cloud-python/issues/6375) for details.

**Comment by theacodes** [comment]
@crwilcox can you investigate? I've yet to see this error from the server side.

**Comment by someone1** [comment]
I'm also getting this issue though its not related to BigQuery. I am using CloudEndpoints ESP docker image locally for development and its been working fine for months though recently I updated it and started getting this error. I tried deleting and setting up the service account again with a new credentials file but get the same error.

To test outside of the docker image - I installed the python-google-auth package and tried going through the steps manually and get this error:


```bash
➜  ~ sudo apt-get install -y python-google-auth python-requests
➜  ~ python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.oauth2 import service_account
>>> from google.auth.transport.requests import AuthorizedSession
>>> 
>>> credentials = service_account.Credentials.from_service_account_file('/path/to/credentials.json').with_scopes(['https://www.googleapis.com/auth/service.management.readonly'])
>>> authed_session = AuthorizedSession(credentials)
>>> response = authed_session.get('https://servicemanagement.googleapis.com/v1/services/XXXXXXXXX/rollouts?filter=status=SUCCESS')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 533, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/google/auth/transport/requests.py", line 198, in request
    self._auth_request, method, url, request_headers)
  File "/usr/lib/python2.7/dist-packages/google/auth/credentials.py", line 121, in before_request
    self.refresh(request)
  File "/usr/lib/python2.7/dist-packages/google/oauth2/service_account.py", line 322, in refresh
    request, self._token_uri, assertion)
  File "/usr/lib/python2.7/dist-packages/google/oauth2/_client.py", line 144, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/usr/lib/python2.7/dist-packages/google/oauth2/_client.py", line 110, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/usr/lib/python2.7/dist-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT: No valid verifier found for issuer.', u'{\n  "error": "invalid_grant",\n  "error_description": "Invalid JWT: No valid verifier found for issuer."\n}')
```

**System Information:**
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
Python 2.7.15rc1
python-google-auth version (1.3.0-2)
python-requests version (2.18.4-2ubuntu0.1)

**Other Notes:**
If I use the oauth2 playground using my account for the same scope and the same API request, it works fine.

**Comment by busunkim96** [comment]
I am going to **close** this for now, as I think we'd need more information to move forward. Please do file a new issue if this is impacting you.

---
**Rationale**:
The original issue from @bencaine1 seems to be describing a *one time* failure to refresh. AFAICT this happens occasionally because of backed service flakiness. If this is happening often we should reach out to internal teams to do more investigation.

@someone1 seems to be describing a different issue (a credentials file consistently returns "invalid_grant"). That is likely a result of the original token becoming invalidated. Since creating a new credentials file did not resolve the issue, the service account may have lost permissions to access the resources. 

https://tools.ietf.org/html/rfc6749#section-5.2


```

         invalid_grant
               The provided authorization grant (e.g., authorization
               code, resource owner credentials) or refresh token is
               invalid, expired, revoked, does not match the redirection
               URI used in the authorization request, or was issued to
               another client.

```
You can take a look at [this StackOverflow post](https://stackoverflow.com/questions/10576386/invalid-grant-trying-to-get-oauth-token-from-google/38433986#38433986) if you're unsure why you're getting this error.
