### ISSUE TITLE
google.auth.transport.Request is called with type(body) == str

### ISSUE THREAD

**Issue by Nikratio** [googleapis/google-auth-library-python#318]
According to eg https://google-auth.readthedocs.io/en/latest/reference/google.auth.html#google.auth.default, classes implementing google.auth.transport.Request will be called with a *body* parameter of type bytes. This makes sense, because the request agent is in no position to decide how a str body should be encoded for transport.

Unfortunately, in some cases the googl.auth module does pass str value. One such call is made in https://github.com/googleapis/google-auth-library-python/blob/137b43ba002d422c68e7bfacdafa54986f38500b/google/oauth2/_client.py#L100, but there may be more.

**Comment by SurferJeffAtGoogle** [comment]
@Nikratio Thank you for reporting this issue.  I apologize for the late reply.  I clicked on the link https://google-auth.readthedocs.io/en/latest/reference/google.auth.html#google.auth.default, and I don't see a discussion of a body parameter or bytes.

Is this issue still reproducible today?  Is there another doc that describes the conflict between the docs and the code?

**Comment by busunkim96** [comment]
The link may have changed since the issue was posted:

`google.auth.transport.Request` documentation says that the body should have type bytes

https://google-auth.readthedocs.io/en/latest/reference/google.auth.transport.html#google.auth.transport.Request
![image](https://user-images.githubusercontent.com/8822365/67342933-7be97c00-f4e8-11e9-8e7b-399533126e20.png)
