### ISSUE TITLE
AuthorizedSession request method parameters

### ISSUE THREAD

**Issue by ShauryaMdn** [googleapis/google-auth-library-python#342]
After adding credentials to the request using AuthorizedSession from google.auth.transport.requests, and then passing this to googleapiclient.discovery.build(), the build function assumes that the http argument is of class httplib2.Http. The request method for httplib2.Http only requires the url, while the request method given from AuthorizedSession also requires method to be specified. This causes me to get a TypeError. Is there a workaround to this?

Stack Trace:
  File "/usr/local/lib/python3.5/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/googleapiclient/discovery.py", line 224, in build
    requested_url, discovery_http, cache_discovery, cache, developerKey)
  File "/usr/local/lib/python3.5/dist-packages/googleapiclient/discovery.py", line 274, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
TypeError: request() missing 1 required positional argument: 'url'

AuthorizedSession.request function definition: 
`def request(self, method, url, data=None, headers=None, **kwargs):`

While for httplib2.Http.request:
`def request(self, uri, method="GET", body=None, headers=None, redirections=DEFAULT_MAX_REDIRECTS, connection_type=None):`

**Comment by busunkim96** [comment]
Unfrotunately it's not possible to use `AuthorizedSession` with `google-api-python-client` because google-api-python-client uses httplib2 under the hood (not requests).

You will have to supply credentials another way when using google-api-python-client. Please see the [Auth documentation](https://github.com/googleapis/google-api-python-client/blob/master/docs/auth.md) for the options available to you.
