### ISSUE TITLE
User Impersonation with Google Service Account and access google calendar in gsuite

### ISSUE THREAD

**Issue by flying-falcon** [googleapis/google-auth-library-python#580]
Hi. I'm trying to implement user impersonation with a google service account. After adding the user to be impersonated as the subject, I get `Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested` error. However, I have added https://github.com/googleapis/google-auth-library-python/blob/master/google/auth/impersonated_credentials.py#L131 to permissions for my project.

Do you have any samples of user impersonation for calendar api? I don't see any samples or usage in Google's documentation. 
Thanks

**Comment by busunkim96** [comment]
@nnkteja Could you share the code you are using to create the credentials and construct the client?

https://googleapis.dev/python/google-auth/latest/user-guide.html?highlight=impersonated#impersonated-credentials is the current example we have for impersonated credentials.

**Comment by mijamo** [comment]
I have tried many things but so far I haven't found a way to make the impersonation work when coming from a Compute Engine Credentials. Trying to use the impersonated_credentials always fails with a 404 error. The only thing that worked was to manually use this answer from StackOverflow: https://stackoverflow.com/a/57092533

I think this should be handled by this library directly because that solution seems quite hacky now.

**Comment by salrashid123** [comment]
`google.auth.impersonated_credentials` is used to assume the identity of a service account (not domain user).  for the latter, it uses domain delegation. 

if you have a service account that is enabled for domain delegation with the correct scope set in the workspace admin console, the snippet is something like this

```python
import google.auth
from google.oauth2 import service_account

target_scopes = ["https://www.googleapis.com/auth/calendar.readonly"]

credentials = service_account.Credentials.from_service_account_file(
    '/path/to/svc_account.json',
    scopes=target_scopes,
    subject='user1@domain.com')


from google.auth.transport.requests import Request
from googleapiclient.discovery import build
import datetime
service = build('calendar', 'v3', credentials=credentials)
now = datetime.datetime.utcnow().isoformat() + 'Z'  # 'Z' indicates UTC time
print('Getting the upcoming 10 events')
events_result = service.events().list(calendarId='primary', timeMin=now,
                                              maxResults=10, singleEvents=True,
                                              orderBy='startTime').execute()
events = events_result.get('items', [])

if not events:
  print('No upcoming events found.')

for event in events:
  start = event['start'].get('dateTime', event['start'].get('date'))
  print(start, event['summary'])
```

see[ domain delegation](https://google-auth.readthedocs.io/en/master/reference/google.oauth2.service_account.html?highlight=domain%20delegation#domain-wide-delegation)

Note, i'm using an actual svc account key based credential because it allows for the `subject=` field to get set

there should be a separate feature request to allow `impersonated_credentials` itself to assume a user's identity (eg,
`user1->impersonate(svc_account_A)-->domain_delgate(user2)->calendar_api`

---

ref https://github.com/googleapis/google-auth-library-python/issues/929
