### ISSUE TITLE
service_account.Credentials is always invalid

### ISSUE THREAD

**Issue by isidentical** [googleapis/google-auth-library-python#690]
Since it doesn't contain a `token`, `credentials.valid` will always result with `False` (even if it is not expired)
https://github.com/googleapis/google-auth-library-python/blob/c731424c7edd15c92fb4b62043ae8e19d8e692e9/google/auth/credentials.py#L71-L78

**Comment by busunkim96** [comment]
Hi,

The code you linked to is the base credentials implementation `google.auth.credentials`. All the credential classes have `refresh` methods that will actually add the token. 

For example, since you mentioned service_account:

https://github.com/googleapis/google-auth-library-python/blob/c731424c7edd15c92fb4b62043ae8e19d8e692e9/google/oauth2/service_account.py#L369-L380

Are you having trouble using a service account credential?

**Comment by isidentical** [comment]
Ah, totally my mistake, didn't notice it all. The reason that I stumbeld against it was, it works well without a refresh (when the `token` is None) (on an API client built with `from googleapiclient.discovery import build`). Is it normal that this works will without `.refresh()`?

**Comment by isidentical** [comment]
When I try to refresh it like this;
```
request = google.auth.transport.requests.Request()
credentials.refresh(request)
```
it justs popes out a weird exception (have to repeat, this credentials object works just fine without refresh)
```
  File "/home/isidentical/.venv38/lib/python3.8/site-packages/google/oauth2/_client.py", line 153, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/home/isidentical/.venv38/lib/python3.8/site-packages/google/oauth2/_client.py", line 124, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/home/isidentical/.venv38/lib/python3.8/site-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_scope: Invalid OAuth scope or ID token audience provided.', '{"error":"invalid_scope","error_description":"Invalid OAuth scope or ID token audience provided."}')

```

**Comment by busunkim96** [comment]
The Google libraries will handle refreshing for you. In other words, there's no need to call `refresh` manually, since it it will happen automatically on the first API call.

For google-api-python-client:

- https://github.com/googleapis/google-api-python-client/blob/91b61d3272de9b5aebad0cf1eb76ca53c24f22f9/googleapiclient/discovery.py#L566-L567
- https://github.com/googleapis/google-api-python-client/blob/91b61d3272de9b5aebad0cf1eb76ca53c24f22f9/googleapiclient/_auth.py#L95-L119
- https://github.com/googleapis/google-auth-library-python-httplib2/blob/02fb2a1dbdb49c9eaca9868c47e9a4afda3ff116/google_auth_httplib2.py#L204

I think you're seeing an error because the credentials need to be scoped before they're refreshed. This is a modification of your code snippet but with scoped credentials.
```py
import google.auth
import google.auth.transport.requests


credentials, _ = google.auth.default(scopes=["https://www.googleapis.com/auth/cloud-platform"])
request = google.auth.transport.requests.Request()

credentials.refresh(request)
```

There's also a note in googleapiclient about scoping the credentials: https://github.com/googleapis/google-api-python-client/blob/91b61d3272de9b5aebad0cf1eb76ca53c24f22f9/googleapiclient/discovery.py#L559-L562

**Comment by isidentical** [comment]
Thanks, issue is resolved when the scopes are provided!
