### ISSUE TITLE
Cloud Function cannot get token from computemetadata server

### ISSUE THREAD

**Issue by donantoniosantos** [googleapis/google-auth-library-python#706]
Have a python cloud function that is trying to access metadata.google.internal and am getting Internal Server Error 500 when trying to get the token or identity. I get a 200 when I access 'http://metadata/computeMetadata/v1/instance/service-accounts' but anything after default or the service account email addr will give me an error 500. Service account has owner privs in the project.

Code:
```
import requests
from requests.auth import HTTPBasicAuth
import requests
import logging

METADATA_HEADERS = {'Metadata-Flavor': 'Google'}


def hello_world(event,context):
    token_url = 'http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token?scopes=https://www.googleapis.com/auth/cloud-platform'
    identity_url = 'http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity?audience=https://oauth2.googleapis.com/token'
    metadata_url = 'http://metadata/computeMetadata/v1/instance/service-accounts/default/token?scope=https://www.googleapis.com/auth/cloud-platform'
    svc_url = 'http://metadata/computeMetadata/v1/instance/service-accounts/default'
    r_token = requests.get(token_url, headers=METADATA_HEADERS)
    r_identity = requests.get(identity_url, headers=METADATA_HEADERS)
    r_metadata = requests.get(metadata_url, headers=METADATA_HEADERS)
    r_svc = requests.get(svc_url, headers=METADATA_HEADERS)

    print(r_token.content)
    print(r_identity.content)
    print(r_metadata.content)
    print(r_svc.content)
```
Output from logs:
```
"b'Could not fetch URI /computeMetadata/v1/instance/service-accounts/default/token?scopes=https://www.googleapis.com/auth/cloud-platform\n'"
"b'Could not fetch URI /computeMetadata/v1/instance/service-accounts/default/identity?audience=https://oauth2.googleapis.com/token\n'"
"b'Could not fetch URI /computeMetadata/v1/instance/service-accounts/default/token?scope=https://www.googleapis.com/auth/cloud-platform\n'"
"b'aliases\nemail\nidentity\nscopes\ntoken\n'"
```

**Comment by busunkim96** [comment]
Hi @donantoniosantos,

I moved this into the Python `google-auth` library repository since this is a question about the Python libraries. It looks like you're trying to fetch a token from the metadata server. https://googleapis.dev/python/google-auth/latest/user-guide.html#compute-engine-container-engine-and-the-app-engine-flexible-environment

The easiest way to get a valid credential object in a Cloud Function is to use Application Default Credentials via the `google-auth` library.


Function code:
```py
import google.auth

credentials, project_id = google.auth.default()
```

If you're using a google cloud client library like `google-cloud-storage`, `google-cloud-pubsub`, etc. you can instantiate the client without passing explicit credentials.

https://cloud.google.com/pubsub/docs/samples/pubsub-create-pull-subscription
```py
from google.cloud import pubsub_v1

publisher = pubsub_v1.PublisherClient()  # this will call google.auth.default() for you
```

If you for whatever reason need to make REST calls directly, google-auth provides a `AuthorizedSession` that will apply the token to the header in all the requests.

https://googleapis.dev/python/google-auth/latest/user-guide.html#requests

```py
import google.auth
from google.auth.transport.requests import AuthorizedSession

credentials, project_id = google.auth.default()
authed_session = AuthorizedSession(credentials)

response = authed_session.get(
    'https://www.googleapis.com/storage/v1/b')
```
